### PR TITLE
NEPT-1981: Fix the missing text in the EC Logo (in some pages).

### PR DESCRIPTION
**Pull request by amd-miri**

### CODE REVIEW

**Comment by drupol** [comment]
Thanks for PR! Much appreciated :-)

Could you please [check this component](https://github.com/ec-europa/ec_europa/blob/32cbe0b87a5a5625efd68d524be0116fed496700/templates/site_header/site_header.component.inc#L72), I think this is "on purpose".

**Comment by amd-miri** [comment]
Thanks @drupol, I see now.
But I don't see why we're use the full version only on the home page. Because on on ECL, on all pages, they have the logo with text.

**Comment by drupol** [comment]
I have to find the information somewhere on Jira, I think it's how ECL is supposed to work... I'll be back at you quickly.

**Comment by drupol** [comment]
@amd-miri I've asked to @yhuard and the text alongside needs to be visible all the time.

Your PR make sense, but then do you mind to add a commit to remove the "if" condition in [that component](https://github.com/ec-europa/ec_europa/blob/32cbe0b87a5a5625efd68d524be0116fed496700/templates/site_header/site_header.component.inc#L72)?

**Comment by amd-miri** [comment]
@drupol the requested change is done in both PR. ;)

**Pull request merged**
