### PR TITLE
NEPT-1064: Implements the expandable component.

### PR DESCRIPTION
**Pull request by voidtek**
### Description

Implement the new expandable component

### Change log

- Changed: Update the definition of the expandable component.
- Added: Add the component qt_accordion for the contrib module Quicktabs - based on the expandable component.

### Commands

```sh
no commands

```

### CODE REVIEW

**Comment by drupol** [comment]
Buttons should be in the form indeed, it would be much easier to manage.
Now, regarding the rest of your comment, I don't see the point.
A form is just a render array with `'#theme' => 'form'` inside and we can do what we want inside.
It's much flexible that being limited by the current implementation.

**Comment by drupol** [comment]
:heart:

**Comment by drupol** [comment]
Shouldn't it be in a follow up ticket ?

**Comment by Fefaine** [comment]
I don't think so, we created an expandable template that cannot be used in any of the feature we provide (faqs, quicktabs, nexteuropa formatters)
So i don't see the point of this code if we merge it now. Furthermore there is more than enough time left on the ticket. Since the expandable was working before, i think this ticket should fix this.

**Comment by drupol** [comment]
allrighty

**Comment by Fefaine** [comment]
I did first round of QA and i approve

**Comment by netlooker** [comment]
I second @Fefaine opinion. Component works as expected.

**Comment by netlooker** [comment]
:+1:

**Pull request merged**
